sudo: required

services:
  - docker
language: php
php:
  - 7.1

before_script:
  - docker build -t revenuewire/translation:latest .
  - composer install --optimize-autoloader
script: docker-compose run test
after_success:
  - travis_retry php vendor/bin/coveralls -v