version: '2'
services:
  test:
      image: revenuewire/translation:latest
      volumes:
          - $PWD:$PWD
      links:
          - redis
      command: ./vendor/bin/phpunit
      working_dir: $PWD
      environment:
        - GCT_KEY=$GCT_KEY
        - GCT_PROJECT=$GCT_PROJECT
  redis:
      image: redis:latest
