version: '2'
services:
  test:
      image: php:7-cli
      volumes:
          - $PWD:/code
      links:
          - redis
      command: ./vendor/bin/phpunit
      working_dir: /code
      environment:
        - GCT_KEY=$GCT_KEY
        - GCT_PROJECT=$GCT_PROJECT
  redis:
      image: redis:latest
