version: '2'
services:
  test:
      image: revenuewire/docker-php7-xenial:latest
      volumes:
          - $PWD:/var/www
      links:
          - redis
      command: ./vendor/bin/phpunit
      working_dir: /var/www
  redis:
      image: redis:latest
