version: '2'
services:
  test:
      image: php:7-cli
      volumes:
          - $PWD:/code
      links:
          - redis
      command: ./vendor/bin/phpunit
      working_dir: /code
  redis:
      image: redis:latest
